# Generated by Django 5.0.2 on 2024-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_poll_polloptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloptions',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
