# Generated by Django 5.0.2 on 2024-03-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usermodel_remove_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
