# Generated by Django 5.0.2 on 2024-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
